# NumPy - Revision

In [1]:
import numpy as np

In [2]:
##numpy version and config
print(np.__version__)
np.show_config()

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']


In [3]:
##null vector of size 10
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
##how to get doccumentation of the numpy add function from the command line
numpy.info(numpy.add)

NameError: name 'numpy' is not defined

In [5]:
##create null vector of size 10 but 5th value is 1
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
##create a vector with value ranging from 10 to 49
Z=np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
##reverse a vector
Z=np.arange(50)
print(Z)
M=Z[::-1]
print(M)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [8]:
##create a 3X3 matrix with value ranging from 0 - 8
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
##find indices of non-zero elements from [1,2,0,0,4,0]
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [10]:
##create a 3X3 identity matrix
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
##create 3X3X3 array with random values
Z=np.random.random((3,3,3))
print(Z)

[[[0.45968331 0.01405816 0.25417282]
  [0.68676492 0.85404377 0.66829068]
  [0.52754872 0.55604343 0.92039409]]

 [[0.64409652 0.84385557 0.92430789]
  [0.74109034 0.32824763 0.35865095]
  [0.58570232 0.12479009 0.90913783]]

 [[0.97161113 0.05392532 0.34854322]
  [0.67822547 0.22923957 0.96134574]
  [0.82148834 0.58076038 0.01865412]]]


In [12]:
##create 10X10 array with random values and find the maximum and minimum values
Z=np.random.random((10,10))
print(Z)
Zmin,Zmax=Z.min(),Z.max()
print(Zmin,Zmax)

[[0.21196958 0.02104962 0.93281846 0.93474659 0.41545206 0.00620738
  0.66575947 0.96183851 0.86055416 0.63876256]
 [0.07482367 0.19243131 0.12982541 0.51119258 0.77127119 0.85096328
  0.96413815 0.83253655 0.7454455  0.12650445]
 [0.37186803 0.86127404 0.32824289 0.11294618 0.31502694 0.9809358
  0.88200477 0.62279314 0.90151408 0.86515874]
 [0.20553221 0.63115146 0.05758977 0.33996322 0.18678082 0.34274496
  0.35000605 0.50656841 0.5676152  0.0892666 ]
 [0.71498947 0.03084597 0.43379183 0.30369271 0.72814804 0.30002465
  0.74552575 0.79682564 0.71411114 0.18722044]
 [0.37365297 0.38333938 0.59908172 0.79405283 0.59681398 0.69071878
  0.30364968 0.34780717 0.43385311 0.03853011]
 [0.84202428 0.40265388 0.88522524 0.38381501 0.60650598 0.2989245
  0.83125149 0.06015694 0.51360122 0.34334739]
 [0.38993007 0.72508132 0.0770315  0.59732734 0.01714149 0.75006775
  0.67070818 0.4180776  0.96548874 0.66695664]
 [0.65269799 0.2245654  0.35458557 0.63277728 0.45493177 0.62738045
  0.58525268 0

In [13]:
##create a random vector of size 30 and find the mean value
Z=np.random.random(30)
print(Z)
m=Z.mean()
print(m)

[0.2665068  0.30233527 0.9042068  0.31823779 0.41950658 0.37428019
 0.63220676 0.61218865 0.61648502 0.65259101 0.45202175 0.5243143
 0.64824638 0.01866653 0.25132936 0.67199278 0.17006574 0.90865833
 0.03896848 0.44607617 0.29600668 0.57728891 0.2070979  0.28773455
 0.84787805 0.85538369 0.90233996 0.20110511 0.9617945  0.75709304]
0.5040869035954436


In [14]:
#create a 2D array with one on the border and zero inside
Z=np.ones((10,10))
print(Z)
Z[1:-1,1:-1]=0
print(Z)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
##what is the result of the following expression
0*np.nan
np.nan==np.nan
np.inf>np.nan
np.nan-np.nan
0.3==3*0.1

False

In [16]:
3*0.1 ## strange

0.30000000000000004

In [17]:
##create a 5X5 matrix with a value 1,2,3,4 just below the diagonal
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [18]:
Z=np.diag(np.arange(4))
print(Z)

[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [19]:
Z=np.diag(np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]]


In [20]:
Z=np.diag(1+np.arange(4))
print(Z)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [21]:
Z=np.diag(1+np.arange(4),k=-2)
print(Z)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]


In [22]:
##create a 8X8 matrix and fill it with a checkerboard pattern
Z=np.zeros((8,8),dtype=int)
print(Z)
Z[1::2,::2]=1
print(Z)
Z[::2,1::2]=1
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
Z=np.random.random((3,3))
print(Z)
Z[0:1,2]=1
print(Z)

[[0.66095535 0.33190773 0.88767141]
 [0.51068627 0.6266346  0.84168302]
 [0.35434129 0.67008201 0.45789963]]
[[0.66095535 0.33190773 1.        ]
 [0.51068627 0.6266346  0.84168302]
 [0.35434129 0.67008201 0.45789963]]


In [24]:
##consider a (6,7,8) shaped array, what is the index of the 100th element
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [25]:
Z=np.random.random((6,7,8))
print(Z)
Z[1,5,4]

[[[0.99868013 0.33313558 0.40682509 0.72123399 0.14456708 0.40643292
   0.10861984 0.04427265]
  [0.82074041 0.22569867 0.07022399 0.81215461 0.31367879 0.41784147
   0.41512808 0.55375395]
  [0.60635304 0.47707538 0.66668549 0.29257157 0.77464984 0.94114668
   0.74610091 0.00621659]
  [0.26553738 0.16599901 0.57878011 0.44763654 0.8449365  0.32355789
   0.6866395  0.54638988]
  [0.20002858 0.30707912 0.2271084  0.13473295 0.33233849 0.46240804
   0.89307861 0.78622749]
  [0.89592301 0.11913186 0.90701175 0.01200462 0.59766781 0.66135451
   0.39767928 0.95935074]
  [0.14275211 0.7607999  0.23655439 0.95200936 0.05940107 0.67651671
   0.01923498 0.1699413 ]]

 [[0.39263796 0.84955943 0.40059012 0.16082692 0.147425   0.72251843
   0.82450186 0.1613562 ]
  [0.0158012  0.53608276 0.54944421 0.60181433 0.97233288 0.26461914
   0.07947113 0.29241688]
  [0.13233386 0.16010051 0.23154563 0.36783755 0.48442157 0.29013429
   0.97417211 0.30259561]
  [0.0376864  0.21170197 0.23337007 0.49200542 0

0.6422113998524308

In [26]:
##create a checkboard 8X8 using a tile function
Z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
## Normalise a 5X5 random matrix
Z=np.random.random((5,5))
print(Z)
Zmax,Zmin=Z.max(),Z.min()
Z=(Z-Zmin)/(Zmax-Zmin)
print(Z)

[[0.3365661  0.09588853 0.73859294 0.06031364 0.54603694]
 [0.09769397 0.61642652 0.58086431 0.46671017 0.41287403]
 [0.30750155 0.33622075 0.15383707 0.57740929 0.06326225]
 [0.64738376 0.08351857 0.08457762 0.38124754 0.45730152]
 [0.33514461 0.56098498 0.96272896 0.97754817 0.08655783]]
[[0.30117974 0.03878494 0.73948296 0.         0.52955191]
 [0.04075329 0.606293   0.56752189 0.4430672  0.38437322]
 [0.26949259 0.30080323 0.10196239 0.5637551  0.00321467]
 [0.64004363 0.0252988  0.02645341 0.34989296 0.43280956]
 [0.29962999 0.54584877 0.9838436  1.         0.0286123 ]]


In [28]:
Z=np.arange(0,20,2)
print(Z)
Zmax,Zmin=Z.max(),Z.min()
Z=(Z-Zmin)/(Zmax-Zmin)
print(Z)

[ 0  2  4  6  8 10 12 14 16 18]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [29]:
##create a custom dtype that describe a color as four unsigned bytes(RGBA)
color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])

C:\Users\MOHAMM~1\AppData\Local\Temp/ipykernel_2628/3490378983.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])


In [30]:
##multiply a 5X3 matrix by a 3X2 matrix (real matrix product)
Z=np.dot(np.random.random((5,3)),np.random.random((3,2)))
print(Z)

[[0.66098579 0.69456488]
 [0.33761133 1.27235249]
 [0.56259933 1.38225413]
 [0.38092024 0.90674159]
 [0.09830757 0.50614072]]


In [31]:
##Given a 1D array, negate all elements which are between 3 and 8 in place.
Z=np.arange(11)
Z[(3<Z&Z>=8)] =-1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
##Result of the following expression
Z=np.arange(11)
print(Z)

In [ ]:
Z**Z

In [ ]:
0**0

In [ ]:
10**10

In [ ]:
9**9

In [ ]:
2<<Z>>2

In [ ]:
Z<-Z

In [ ]:
1j*Z

In [ ]:
Z/1/1

In [ ]:
5<<Z>>5

In [ ]:
np.array(0)//np.array(0)

np.array(0)//np.array(0.)
np.array(0)/np.array(0)
np.array(0)/np.array(0.)

In [ ]:
##How to round away from zero a float array?
Z=np.random.uniform(-10,+10,10)
print(Z)
print(np.trunc(Z))
print(np.copysign(0.5,Z))
print(np.trunc(Z+np.copysign(0.5,Z)))

In [ ]:
##extract an integer part of an array using 5 different method
Z=np.random.uniform(0,10,10)
print(Z)
print(Z-Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

In [ ]:
##create a 5X5 matrix with row values ranging from 0 to 4:
Z=np.zeros((5,5))
Z+=np.arange(5)
print(Z)


In [ ]:
##Consider a generator function that generates 10 integers and use it to build an array
def generator():
    for x in xrange(10):
        yield x
Z=np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

In [ ]:
##create a vector of size 10 with values ranging from 0 to 1,both excluded
M=np.linspace(0,1,12,endpoint=True)[1:-1]
print(M)

In [ ]:
##create a random vector of size 10 and sort it
Z=np.random.random(10)
print(Z)
Z.sort()
print(Z)



In [ ]:
##How to sum a small array faster than np.sum?
Z=np.arange(10)
print(Z)
np.add.reduce(Z)

In [ ]:
##Consider two random array A and B,Check if they are equal
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
equal=np.allclose(A,B)
print(equal)

In [32]:
##make an array immutable(read-only)
Z=np.zeros(10)
Z.flags.writeable=False
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [33]:
##Create a random 10X2 matrix representing cartesian coordinates, convert them to polar coordinates
Z=np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.22556361 1.20828692 0.48508725 0.90411714 0.18305323 0.76981353
 0.33330925 0.1330105  1.02594149 0.70957064]
[0.02895794 0.61180762 0.15800563 1.0505968  0.23227287 0.08277558
 1.38569291 0.03728282 1.15687634 0.65147413]


In [34]:
##create random vector of size 10 and replace the maximum value by 0
Z=np.random.random(10)
Z[Z.argmax()]=0
print(Z)

[0.50197188 0.         0.44972706 0.49032782 0.84957349 0.57648548
 0.12945476 0.23086906 0.23616936 0.14207161]


In [35]:
##create a structured array with x and y coordinate covering the  [0,1]X[0,1] area
Z=np.zeros((10,10),[('x',float),('y',float)])
print(Z)
Z['x'],Z['y']=np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]]
[[(0.        , 0.        ) (0.11111111, 0.       

In [36]:
##GIVEN TWO ARRAYS, x AND y Construct the cauchy matrix C(Cij=1/(xi-yj))
X=np.arange(8)
print(X)
Y=X+0.5
print(Y)
C=1.0/np.subtract.outer(X,Y)
print(C)
print(np.linalg.det(C))

[0 1 2 3 4 5 6 7]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


In [37]:
##print the minimu and maximum representablr values fo each numpy scalar type
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [38]:
##How to print all the values of an array?
np.set_printoptions(threshold=100)
Z=np.zeros((25,25))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [39]:
Z=np.arange(100)
print(Z)
v=np.random.uniform(0,100)
print(v)
index=(np.abs(Z-v)).argmin()
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
12.468412120392703
12


In [40]:
##create a structured array representing a position (x,y) and a color (r,g,b)
Z=np.zeros(10,[('x', float, 1),('y',float,1)],('color',[('r',float,1),('g',float,1),('b',float,1)]))
print(Z)

C:\Users\MOHAMM~1\AppData\Local\Temp/ipykernel_2628/1257644485.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z=np.zeros(10,[('x', float, 1),('y',float,1)],('color',[('r',float,1),('g',float,1),('b',float,1)]))


TypeError: order must be str, not tuple

In [ ]:
##consider a random vector vector with shape (100,2)representing coordinates, find point by point distances
Z=np.random.random((10,2))
X,Y=np.atleast_2d(Z[:,0]),np.atleast_2d(Z[:,1])
D=np.sqrt((X-X.T)**2+(Y-Y.T)**2)
print(D)


In [ ]:
##How to convert a float(32 bits) array into an int(32 bits) in place
Z=np.arange(10,dtype=np.int32)
Z=Z.astype(np.float32,copy=False)

In [ ]:
##what is the equivalent of enumerate for numpy arrays?
Z=np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index,value)
for index in np.ndindex(Z.shape):
    print(index,Z[index])

In [ ]:
##Generate a generic 2D Gaussian-like array
X,Y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D=np.sqrt(X*X+Y*Y)
sigma,mu=1.0,0.0
G=np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)

In [ ]:
##how to randomly place p elements in a 2D array
n=10
p=3
Z=np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
print(Z)

In [41]:
##subtract the mean of each row of a matrix
X=np.random.rand(5,10)
Y=X-X.mean(axis=1,keepdims=True)
print(X)
print(Y)

[[0.600614   0.35459453 0.64972813 0.78628167 0.71038435 0.14615155
  0.91781954 0.3264223  0.73506051 0.01699531]
 [0.8807575  0.18128158 0.12214092 0.52651163 0.15394139 0.56416709
  0.59926737 0.40518133 0.56129278 0.16108172]
 [0.7033481  0.32075745 0.17988013 0.85563391 0.0257153  0.78109107
  0.08233284 0.86260993 0.13341551 0.87742915]
 [0.36667116 0.25575248 0.44367022 0.24629362 0.55935542 0.5685066
  0.05770014 0.29283884 0.82804925 0.74938849]
 [0.64736173 0.33769442 0.79378408 0.84227514 0.25053406 0.79960735
  0.53963976 0.28444893 0.46382725 0.88800492]]
[[ 0.07620881 -0.16981066  0.12532294  0.26187648  0.18597916 -0.37825364
   0.39341435 -0.19798289  0.21065532 -0.50740988]
 [ 0.46519517 -0.23428075 -0.29342141  0.1109493  -0.26162094  0.14860476
   0.18370504 -0.010381    0.14573045 -0.25448061]
 [ 0.22112677 -0.16146389 -0.3023412   0.37341258 -0.45650604  0.29886973
  -0.3998885   0.38038859 -0.34880583  0.39520781]
 [-0.07015146 -0.18107014  0.0068476  -0.190529   

In [42]:
##how do i sort an array by an nth column
Z=np.random.randint(0,3,(3,10))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 2 0 2 0 1 1 1 2 1]
 [2 1 0 0 2 2 0 2 1 2]
 [0 0 0 2 2 0 0 2 1 1]]
[[0 0 0 2 2 0 0 2 1 1]
 [2 1 0 0 2 2 0 2 1 2]
 [2 2 0 2 0 1 1 1 2 1]]


In [43]:
##how to tell if a given 2D array has null columns?
Z=np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [44]:
##find the nearest value from a given value in an array
Z=np.random.uniform(0,1,10)
print(Z)
z=0.5
m=Z.flat[np.abs(Z-z).argmin()]
print(m)

[0.46845825 0.52099468 0.46250534 0.55407467 0.99599391 0.82372923
 0.48182894 0.12575898 0.60657421 0.92723965]
0.48182893933142945


In [45]:
##create an array class that has a name attribute
class NamedArray(np.ndarray):
    def __new__(cls,array,name="no name"):
        obj=np.asarray(array).view(cls)
        obj.name=name
        return obj
    def __array_finalize__(self,obj):
        if obj is None: return
        self.info=getattr(obj,'name',"no name")
Z=NamedArray(np.arange(10),"range_10")
print(Z.name)

range_10


In [48]:
##Consider a given vector , how to add 1 to each elemet indexed by a second vector(be careful with repeated indices)
Z=np.ones(10)
print(Z)
I=np.random.randint(0,len(Z),20)
print(I)
Z+=np.bincount(I,minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 3 0 9 5 4 8 2 6 7 0 2 2 6 1 5 3 6 5 0]
[4. 2. 4. 3. 2. 5. 4. 2. 2. 2.]


In [47]:
##How to accumulate elements of a vector(X) to an array (F) based on a index list(I)?
X=[1,2,3,4,5,6]
I=[1,3,9,3,4,1]
F=np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [49]:
##considering a (w,h,3) image of (dtype=ubyte),compute the numbers of unique colors
w,h=16,16
I=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F=I[...,0]*256*256+I[...,1]*256+I[...,2]
n=len(np.unique(F))
print(np.unique(I))

[0 1]


In [55]:
##considering a four dimension array, how to get over the last two axis at once?
A=np.random.randint(0,10,(3,4,3,4))
sum=A.reshape(A.shape(:,-2)+(-1,)).sum(axis=-1)
print(sum)

SyntaxError: invalid syntax (Temp/ipykernel_2628/3281941858.py, line 3)

In [ ]:
##consider a one dimensional vector D